export const companyBackgroundTypes = {
  SET_LOADING: 'SET_LOADING',
  GET_COMPANY_BACKGROUND: 'GET_COMPANY_BACKGROUND',
  CREATE_COMPANY_BACKGROUND: 'CREATE_COMPANY_BACKGROUND',
  GET_COMPANY_BACKGROUND_DETAIL: 'GET_COMPANY_BACKGROUND_DETAIL',
  UPDATE_COMPANY_BACKGROUND: 'UPDATE_COMPANY_BACKGROUND',
};
