export const resourceActionTypes = {
  GET_RESOURCE_HUBS: '[RESOURCE_HUBS] GET RESOURCE_HUBS',
  SET_LOADING: '[RESOURCE_HUBS] SET LOADING',
  SET_FILTER: '[RESOURCE_HUBS] SET FILTER',
  SET_SUBMITTING: '[RESOURCE_HUBS] SET SUBMITTING',
  RESET_FILTER: '[RESOURCE_HUBS] RESET FILTER',
  CREATE_RESOURCE_HUB: '[RESOURCE_HUBS] CREATE_RESOURCE_HUB',
  UPDATE_RESOURCE_HUB: '[RESOURCE_HUBS] UPDATE_RESOURCE_HUB',
  GET_RESOURCE_HUB_DETAIL: '[RESOURCE_HUBS] GET_RESOURCE_HUB_DETAIL',
  GET_ORGANZATIONS: '[RESOURCE_HUBS] GET_ORGANZATIONS',

  /*==========Client List ==========*/
  SET_RESOURCE_QUERIES: '[SET_RESOURCE_QUERIES] set resource hub list',
  SET_RESOURCE_HUBS_LOCAL_STATES:
    '[RESOURCE_HUBS] set resource hub list local states',
  RESET_RESOURCE_HUBS_QUERIES:
    '[RESET_RESOURCE_HUBS_QUERIES] reset resource hub list queries',
  GET_RESOURCE_HUBS_LIST:
    '[GET_RESOURCE_HUBS_LIST] get resource hub list success',

  /*==========Client Detail ==========*/
  GET_RESOURCE_HUBS_DETAIL:
    '[GET_RESOURCE_HUBS_DETAIL] get resource hub detail request',
};
