export const GET_PUBLIC_TOKEN = 'GET_PUBLIC_TOKEN';
export const CONTACTS_REQUEST = 'CONTACTS_REQUEST';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_FAILED = 'CONTACTS_FAILED';
