export const userPermissionType = {
  GET_USER_PERMISSIONS: 'GET_USER_PERMISSIONS',
  SELECT_USER_PERMISSIONS: 'SELECT_USER_PERMISSIONS',
  UPDATE_USER_PERMISSIONS: 'UPDATE_USER_PERMISSIONS',
  SET_LOADING: 'SET_LOADING',
  SET_PERMISSION_PARAMS: 'SET_PERMISSION_PARAMS',
  SET_TEMP_PERMISSIONS: 'SET_TEMP_PERMISSIONS',
};
