export const classificationTypes = {
  GET_SECTORS: '[CLASSIFICATION] GET SECTORS',
  GET_PILLARS: '[CLASSIFICATION] GET PILLARS',
  GET_ORGANIZATIONS: '[CLASSIFICATION] GET ORGANIZATIONS',
  GET_PROJECT_STATUS: '[Project Status] Request',
  GET_REFERENCE_FILE_TYPES: '[CLASSIFICATION] GET REFERENCE_FILE_TYPES',
};
