export const userVerificationType = {
  // put here all the actions
  USER_VERIFICATION_REQUEST: 'USER_VERIFICATION_REQUEST',
  USER_VERIFICATION_SUCCESS: 'USER_VERIFICATION_SUCCESS',
  USER_VERIFICATION_FAILED: 'USER_VERIFICATION_REQUEST',

  TOGGLE_USER_VERIFICATION_STATUS_REQUEST:
    'TOGGLE_USER_VERIFICATION_STATUS_REQUEST',
  TOGGLE_USER_VERIFICATION_STATUS_SUCCESS:
    'TOGGLE_USER_VERIFICATION_STATUS_SUCCESS',
  TOGGLE_USER_VERIFICATION_STATUS_FAILED:
    'TOGGLE_USER_VERIFICATION_STATUS_FAILED',
  SET_LOADING_LIST: 'SET_LOADING_LIST',
};
