export const AuthActionTypes = {
  LOGIN: 'LOGIN',
  GET_AUTHORIZE_TOKEN: 'GET_AUTHORIZE_TOKEN',
  LOGOUT: 'LOGOUT',
  GET_PUBLIC_TOKEN: 'GET_PUBLIC_TOKEN',
  SET_GLOBAL_LOADING: 'SET_GLOBAL_LOADING',
  GET_ORGANIZATION_NAMES: 'GET_ORGANIZATION_NAMES',
  GET_ORGANIZATION_TYPES: 'GET_ORGANIZATION_TYPES',
  GET_PILLARS: 'GET_PILLARS',
  GET_SECTORS: 'GET_SECTORS',
};
