export const userTypes = {
  // put here all the actions
  GET_USERS: '[USERS] GET USERS',
  GET_USER: '[USERS] GET USER',
  SET_LOADING: '[USERS] SET LOADING',
  SET_FILTER: '[USERS] SET FILTER',
  SET_SUBMITTING: '[USERS] SET SUBMITTING',
  RESET_FILTER: '[USERS] RESET FILTER',
  GET_USER_ROLES: '[USERS] GET USER ROLES',
  GET_ORGANIZATION: '[USERS] GET ORGANIZATION',
  GET_PROJECTS: '[USERS] GET PROJECTS',
};
